### ISSUE TITLE
Heroku Testing for Python

### ISSUE THREAD

**Issue by vntkumar8** [vntkumar8/covid-dashboard#1]
Check [this link](https://panel.holoviz.org/user_guide/Server_Deployment.html) for how to deploy python panel apps using heroku.

**Comment by VHKA1729** [comment]
I am exploring Heroku. Will get this done.

**Comment by vntkumar8** [comment]
@VHKA1729  I have pushed some new changes in `9thMay-v4.ipynb`.
It will be nice if you could try with hosting this notebook in heroku.So that we can try sharing this w/ AB.

------

[This link](https://panel.holoviz.org/user_guide/Server_Deployment.html) has information on how to do this. `requirements.txt` and `procfile` is also available in repo.

**Comment by VHKA1729** [comment]
I have gone through the link. I will do this by tonight.

**Comment by VHKA1729** [comment]
Deployed at https://covid19kol.herokuapp.com/

There is some error. Fixing that.

**Comment by vntkumar8** [comment]
Yes, This is the error I was also getting.
Did you tried running this in your local machine?

**Comment by VHKA1729** [comment]
Not till now. 
I am downloading the CLI tools for going through the logs.

**Comment by VHKA1729** [comment]
It is running on local machine.
Probably need to look at requirements.txt for Heroku.
Will do by today evening

**Comment by VHKA1729** [comment]
Unforked repo is now deployed for 9th May-v4

**Comment by vntkumar8** [comment]
Awesome.
