### ISSUE TITLE
Wireframes for Dashboard

### ISSUE THREAD

**Issue by VHKA1729** [vntkumar8/covid-dashboard#6]
@vntkumar8 @Subhasis26 @prasadb12  Please draw and upload the wireframes by tonight. Have a look at different dashboards (not necessarily limited to COVID). We will discuss them tomorrow.

**Comment by vntkumar8** [comment]
my try.

>

**Comment by vntkumar8** [comment]
[Uploading wireframe-vk (1).pdf…](My try.)

**Comment by vntkumar8** [comment]
check my try.
[wireframe-vk (1).pdf](https://github.com/vntkumar8/covid-dashboard/files/4616304/wireframe-vk.1.pdf)

**Comment by VHKA1729** [comment]
We can use some elements from this as well:

![image](https://user-images.githubusercontent.com/60542389/81748593-bbe57000-94c7-11ea-99fe-43e3e1aef3c8.png)

This is only for India. 
For the States, we can have something similar.

**Comment by VHKA1729** [comment]
When we give drop-downs for a lot of things, it enables us to present data in a concise manner. However, it might be insightful to compare two graphs, side-by-side, when someone looks up our figures. Can we build such an feature?

Bar-plots mentioned in @vntkumar8's wireframe are good. 

How can we make the whole thing more visually appealing?

**Comment by prasadb12** [comment]
[wireframe_pb1.pdf](https://github.com/vntkumar8/covid-dashboard/files/4621344/wireframe_pb1.pdf)

**Comment by Subhasis26** [comment]
[Wireframes_Subhasis.pdf](https://github.com/vntkumar8/covid-dashboard/files/4621449/Wireframes_Subhasis.pdf)

**Comment by VHKA1729** [comment]
@prasadb12 the comments are visible. I second that the % districts in each zone should be displayed. In fact, we can do that even at the national level and then trickle down to the States.

@Subhasis26 : agreed with the point on bar plots as well as the scaling feature.

We should also try that the metrics computed on national and state level remain same. What can be computed at State level can definitely be computed at national level.

**Comment by vntkumar8** [comment]
Finalalized view after discussions.
![Dashboard_Wireframe_v1_India](https://user-images.githubusercontent.com/7812689/82136990-39dfa900-9831-11ea-984c-2c0952ecd8b1.jpg)
