### ISSUE TITLE
Moving Average Plot 

### ISSUE THREAD

**Issue by vntkumar8** [vntkumar8/covid-dashboard#8]
Note: fix a moving average window. (3day/5day/week)

A drop down plot of various cases viz: active/confirmed/recovered/deceased.

Caveat: If we get a dataframe of time series data then, `df.hvplot()` plots the chart but x-axis has cluttered view. 
![image](https://user-images.githubusercontent.com/7812689/82138585-25a2a880-983f-11ea-96a4-529814023c2f.png)

Should find a way how to resolve this cluttered x-axis ticks view.

**Comment by prasadb12** [comment]
convert the date column to **date format**, the cluttered issue is resolved.

**Comment by Subhasis26** [comment]
I have fixed the rolling window with 3 day and the drop down of various plots.
Let me know how to upload the code file. I am getting confused whether to commit to any branch?

**Comment by VHKA1729** [comment]
Commit to the 'master'. Name your file appropriately.

**Comment by Subhasis26** [comment]
I have uploaded the file which is the code for the Moving average plot.

**Comment by vntkumar8** [comment]
Thanks @Subhasis26  It is working fine but the x-axis labels are still very cluttered

![image](https://user-images.githubusercontent.com/7812689/82183273-47fdfa00-9903-11ea-8385-fd3bba29f343.png)
I think @prasadb12  has suggested some wayaround. Did you implemented this in your file?

**Comment by Subhasis26** [comment]
Yes, I had done that in my file. It was working fine.
I had done this before:
state_df['Date'] = pd.to_datetime(state_df['Date'])
